### PR TITLE
feature/render-meta-tags-for-sources

### LINKED ISSUE #192: Render meta tags for sources
### Describe the feature
Currently it's possible to add meta tags to sources in the .yml file, but they aren't rendered in dbt docs.  
This feature is currently available for tables (see [this mr](https://github.com/fishtown-analytics/dbt-docs/pull/73)).

### Describe alternatives you've considered  
N/A

### Additional context
Not database specific.

### Who will this benefit?
This will be beneficial for everyone that wants to add additional meta tags for their sources (equally to the functionality for tables). 

### Are you interested in contributing this feature?
Yes, I will try to contribute. ☺️

### PR DESCRIPTION
**Pull request by diegodewilde**
resolves #192 

### Description

This PR will adds the functionality to render `meta` tags from sources in the .yml file in dbt docs.

### CODE REVIEW

**Comment by diegodewilde** [comment]
@drewbanin Signed CLA.

**Comment by jtcohen6** [comment]
@cla-bot check

**Review by jtcohen6 — COMMENTED** [review]
Thanks for the contribution @diegodewilde, this looks good. In the future, we may want to think about whether meta properties defined on sources should be inherited by source tables; and if so, whether that inheritance should be additive or clobbering. In the meantime, this is definitely an improvement over status quo.

Could you add a changelog entry, and add yourself to the list of contributors?

**Comment by diegodewilde** [comment]
You're welcome @jtcohen6, happy to be able to support! 
I've added a changelog entry, and added myself to the list of contributors as well.

**Review by jtcohen6 — APPROVED** [review]

**Pull request merged**
