### PR TITLE
Added search by tag name

### PR DESCRIPTION
**Pull request by rmgpinto**
Added two changes:

1. Search for tags (layout similar to search for columns);
2. Tags are now clickable and navigate directly to a search of that tag name.

### CODE REVIEW

**Comment by rmgpinto** [comment]
[jaffle_shop](https://github.com/fishtown-analytics/jaffle_shop) needs to have `tags` to test this PR.

**Comment by drewbanin** [comment]
hey @rmgpinto - thanks for making that `jaffle-shop` update! You'll need to re-compile the `jaffle-shop` project and copy the resulting `.json` files into the `data/` dir. We could automate this in the CI process, bit it's currently manual.

Let me know if you'd like a hand with that - happy to help!

**Comment by rmgpinto** [comment]
If you wouldn't mind. I'm getting an error running `dbt seed` on `jaffle_shop`:

```
Runtime Error in seed raw_orders (data/raw_orders.csv)
  Cannot escape <class 'datetime.date'>
```

**Comment by drewbanin** [comment]
I just merged this PR: https://github.com/fishtown-analytics/dbt-docs/pull/33

You should be able to pull in master to see tags in the CI build!

**Comment by rmgpinto** [comment]
Thanks @drewbanin.
The CI build seems very nice.

**Pull request merged**
