### PR TITLE
Added search by columns.

### PR DESCRIPTION
**Pull request by rmgpinto**
@drewbanin I've added the ability to search by columns.

Changes:

- `project_service.js`: refactored `fuzzySearchObj` function to allow search by `string` or `object` (json tree). On a later PR I can add search by `array` which will allow to search for model tags as well.
- `search.html`: changed html to reflect layout shown in screenshot (see below). The layout has a _Show More..._  to expand the results of more than 3 columns, just like at the end of the model search results.
- `search.js`: added `columnFilter` and `limitColumns` functions to execute the search logic.

Screenshot: [link](https://imgur.com/hLw96Qi)

### CODE REVIEW

**Comment by drewbanin** [comment]
@rmgpinto this is amazing!! Thanks for opening this PR! I think you're the first external contributor to the docs website :)

I'd love to get this merged - let me play around with this today and get back to you early next week!=

**Comment by drewbanin** [comment]
Hey @rmgpinto - I just merged this PR to add CI to the dbt-docs repo: https://github.com/fishtown-analytics/dbt-docs/pull/24

Can you pull `master` and merge it into your branch then re-push? We'll be able to see a sample build with your changes!

**Comment by rmgpinto** [comment]
@drewbanin all done.

**Comment by rmgpinto** [comment]
Thanks for the suggestion @drewbanin, I've reflected that on the layout and it looks better now :)

I had to add `$event.stopPropagation()` to prevent the click on _Show more..._ columns to navigate to the model page.

**Comment by rmgpinto** [comment]
Thanks @drewbanin!

**Pull request merged**
