### PR TITLE
Use new logo

### PR DESCRIPTION
**Pull request by clrcrl**
Copied the svg from [here](https://github.com/fishtown-analytics/www.getdbt.com/blame/master/_config/_includes/svg/logo.svg)

Adding Drew as a reviewer as I'm not sure how to release this :)

### CODE REVIEW

**Comment by drewbanin** [comment]
@amy-byrum can you give the updated deploy preview another look?

**Comment by amy-byrum** [comment]
Beautiful! 👍

**Comment by clrcrl** [comment]
Does this get merged into master? Not sure what the gitflow is for this repo

**Comment by drewbanin** [comment]
@clrcrl I can merge and release this...

**Comment by clrcrl** [comment]
Go for it!

**Pull request merged**
